theme: jekyll-theme-cayman
api_url: https://github.com/FastCGI-Archives
is_project_page: true
repository_url: https://github.com/FastCGI-Archives
repository_name: FastCGI Github Archives
owner_url: https://github.com/mcarbonneaux
owner_name: mcarbonneaux
show_downloads: false
title: FastCGI.com Github Archives
description: This is the Github FastCGI Archives of FastCGI.com site.
google_analytics: UA-3441258-6
piwik_analytics: 5
piwik_url: piwik.ch2o.info
keywords: fastcgi, fastcgi specification, fastcgi source, fastcgi php, fastcgi apache, fastcgi iis, fastcgi c++, fastcgi nginx, fastcgi download, fcgi spec, fcgi-spec, fastcgi overview, cgi, protocol specification, php-fpm, apache, mod_proxy_fastcgi, mod_fcgid, mod_fastcgi, fcgi2, fcgi sdk, nginx fastcgi, ngx_http_fastcgi_module, ligthttpd, cherokee, perl, python, ruby
plugins:
  - jekyll-sitemap
